language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode

env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=3.1"
  - "RAILS_VERSION=3.0"
  - "RAILS_VERSION=4.1"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=4.1"
